services:
  julia_code:
    container_name: julia_code
    build:
      context: .
      dockerfile: ./docker/python.Dockerfile
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - GENAI_API_KEY=${GENAI_API_KEY}
      - TEMPERATURE=0.7
      - TOP_P=0.9
      - TOP_K=40
      - MAX_OUTPUT_TOKENS=2048
      - RESPONSE_MIME_TYPE=text/plain
    stdin_open: true
    tty: true

  julia_api_go:
    build:
      dockerfile: ./docker/golang.Dockerfile
      context: .
    image: golang
    restart: always
    container_name: ${APP_NAME}
    ports:
      - "${APP_PORT}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
