required = "{{.field}} é um campo obrigatório"
Name = "Nome"
Description = "Descrição"
SubjectType = "Tipo de Registro"
SubjectID = "ID do Registro"
CauserType = "Tipo de Usuário"
CauserID = "ID do Usuário"
Properties = "Propriedades"
DefaultModel = "Modelo Padrão"
Error = "Erro"
Status = "Status"
BoxID = "ID da Caixa"
Box = "Caixa"
UserID = "ID do Usuário"
User = "Usuário"
DeletedAt = "Deletado em"
WifiSSID = "SSID"
WifiPassword = "Senha"
SharePassword = "Senha de Compartilhamento"
MasterPassword = "Senha Mestre"
MacAddress = "Endereço MAC"
LastSync = "Última Sincronização"
Category = "Categoria"
TemporaryPasswords = "Senhas Temporárias"
ID = "ID"
CreatedAt = "Criado em"
UpdatedAt = "Atualizado em"
Password = "Senha"
Email = "E-mail"
EmailVerifiedAt = "E-mail Verificado em"
RememberToken = "Lembrar Token"
FCMToken = "Token FCM"
Token = "Token"
ResetPasswordToken = "Token de Redefinição de Senha"